version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-broker
    command:
      - redpanda
      - start
      - --smp 1
      - --mode dev-container
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - 19092:19092
      - 9092:9092
  
  # NEW: Redis for high-speed feature lookups
  redis:
    image: redis:alpine
    container_name: redis-store
    ports:
      - 6379:6379